### ISSUE TITLE
IE 11/Safari story explicit default

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#217]
In Safari and IE 11, the story explicit does not default to the series explicit value. Both have errors.

Safari:
undefined is not an object (evaluating 'n.loadRelated')
defaultExplicitToSeries@https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1544:17406
https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1544:17291
__tryOrSetError@https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1:10509

IE 11:
Unable to get property 'loadRelated' of undefined or null reference

TypeError: Unable to get property 'loadRelated' of undefined or null reference
   at t.prototype.defaultExplicitToSeries (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1544:17405)
   at Anonymous function (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1544:17266)
   at e.prototype.__tryOrSetError (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1:10503)
   at e.prototype.next (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1:9679)
   at e.prototype._next (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1:9043)
   at e.prototype.next (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1:8726)
   at e.prototype._subscribe (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:575:13313)
   at t.prototype.subscribe (https://publish-staging.prx.tech/main.b4df1c834f187c6f5560.bundle.js:1:6680)
   at t.prototype.defaultDistributionOverrides (https://publish-staging.prx.t

**Comment by sandikbarr** [comment]
The explicit defaulting was redundant, so that code was removed. No longer an issue. Closing.
