### ISSUE TITLE
Can't make a new series

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#499]
Some users are not able to make a new series in publish
I am able to reproduce
log into publish
create a new series, set the account for the series
when you hit save, you'll get this error:

```
TypeError: Cannot read property 'expand' of null
    at l.encode (https://publish.prx.org/main.0f9939048537d2de003f.bundle.js:1:328409)
    at l.t.save (https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:774:76791)
    at n.save (https://publish.prx.org/main.0f9939048537d2de003f.bundle.js:1:391628)
    at Object.handleEvent (https://publish.prx.org/main.0f9939048537d2de003f.bundle.js:1:45310)
    at Object.b [as handleEvent] (https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:127:1463)
    at Object.handleEvent (https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:127:8789)
    at ee (https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:78:1744)
    at https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:92:3225
    at e.object.i [as _next] (https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:188:3896)
    at e.__tryOrUnsub (https://publish.prx.org/vendor.aaa8cba66ec88d9bd7b2.bundle.js:382:160619)
```
the expand seems to be this:
`var l=this.doc.expand("prx:account").replace(""+this.original.accountId,""+this.accountId)`

I was able to make a new series in a different account, but not for some accounts

**Comment by kookster** [comment]
looks like this line:
https://github.com/PRX/publish.prx.org/blob/master/src/app/shared/model/series.model.ts#L133
