### ISSUE TITLE
Error on Search Among Episodes

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#709]
If I navigate to the series episode list page (e.g., https://publish.prx.org/series/38586/list) and the click on `Search among these episodes.` at the bottom, I'm taken to https://publish.prx.org/search;tab=stories;seriesId=38586 and I get an error

```
Error: Uncaught (in promise): TypeError: Cannot read property 'count' of undefined
TypeError: Cannot read property 'count' of undefined
    at e.searchStories (https://publish.prx.org/main.e4e8956da448318d6470.js:1:3287112)
    at https://publish.prx.org/main.e4e8956da448318d6470.js:1:3285758
    at t._next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:99369)
    at t.__tryOrUnsub (https://publish.prx.org/main.e4e8956da448318d6470.js:1:492551)
    at t.next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:491696)
    at t._next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:490764)
    at t.next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:490435)
    at t._subscribe (https://publish.prx.org/main.e4e8956da448318d6470.js:1:48023)
    at t.e._trySubscribe (https://publish.prx.org/main.e4e8956da448318d6470.js:1:99103)
    at t._trySubscribe (https://publish.prx.org/main.e4e8956da448318d6470.js:1:645247)
    at M (https://publish.prx.org/polyfills.7381057dd98ab9cbdf90.js:1:14076)
    at https://publish.prx.org/polyfills.7381057dd98ab9cbdf90.js:1:13174
    at t._next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:99383)
    at t.__tryOrUnsub (https://publish.prx.org/main.e4e8956da448318d6470.js:1:492551)
    at t.next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:491696)
    at t._next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:490764)
    at t.next (https://publish.prx.org/main.e4e8956da448318d6470.js:1:490435)
    at t._subscribe (https://publish.prx.org/main.e4e8956da448318d6470.js:1:48023)
    at t.e._trySubscribe (https://publish.prx.org/main.e4e8956da448318d6470.js:1:99103)
    at t._trySubscribe (https://publish.prx.org/main.e4e8956da448318d6470.js:1:645247)
```

**Comment by sandikbarr** [comment]
This error seems to occur for users with more than 10 series on their accounts.
